### PR TITLE
Bug/update readme

### PR DESCRIPTION
**Pull request by iknight7000**
# Pull Request Template

## Description

This fix will help the new learners coming in so they understand where the project is, what needs to be fixed, and some possible solutions. 

[Video Link Here](https://www.loom.com/share/76ebb5527c034b7ab66855e108abcf3d)

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## How Has This Been Tested?

These changes are being tested now, as you look at the files. 

- [x] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by gaben3722 — APPROVED** [review]
A bunch of small fixes that will improve our documentation, approved.

**Comment by mikecarrier4** [comment]
good documentation

**Review by ChristopherKchilton — APPROVED** [review]
There are still some things we need to adjust to adhere to proper standards. That includes Class naming convention. However this is a good start for the code base.

**Review by pflee1989 — APPROVED** [review]
Great changes for the incoming cohort to start. Thanks for the input.

**Pull request merged**
