### PR TITLE
Used GPT-2 to generate synthetic data for BERT

### PR DESCRIPTION
**Pull request by JAaron93**
Naming: feature/descriptive-name

Reviewers: minimum 2 (Ryan and/or 2 from Web or DS respectively and not the person who submitted PR)

Description: 
  What is the motivation for these changes?

Our NLP classification model lacks enough samples of Ranks 2, 3, & 4 police misconduct. Manual labeling of these data is far too slow, prompting the desire to use synthetic data in its place.

  What specific changes were made?

A simplified GPT-2 text generation notebook, an EDA notebook for the cleaning and conversion of these generated tweets, and hand cleaned generated tweets in .txt format as reference/resource.

Submitter Checklist: 
  - [ ] Small scope (1-2 components)
  - [ ] Not too many concerns in a single commit
  - [x] Remove extraneous comments (code in comments), print statements, to-dos, console.logs, extra fluff
  - [x] Atomic, descriptive commit messages
  - [x] Consistent formatting

Reviewer Checklist:
  - [x] Small scope (1-2 components)
  - [x] Comments, print statements, to-dos, console.logs, extra fluff were removed
  - [x] Give feedback no matter what conversations happened elsewhere, document here
  - [ ] Comment on the line of code itself (blue plus box) in files changed tab

### CODE REVIEW

**Review by Iamlegend-Imani — APPROVED** [review]
@rhiag and @RyanFikejs can I get and extra set of eyes on this one to see if I missed anything?

**Review by rhiag — APPROVED** [review]
This is great work Joshua!

**Review by rhiag — COMMENTED** [review]
Joshua - I believe we may need to generate a few more tweets for Rank 2 labels. Based on your text cleaning notebook looks like we have 500 odd entries for rank 2. We might have a better idea once I retrain BERT on the tweets you've generated. We can take a look at it post that.

**Comment by JAaron93** [comment]
Everything went well with cleaning the data in my EDA notebook. It's just that somehow when using the pandas .to_csv() method to convert my cleaned dataframe into CSVs a lot of the data just runs into each other. Text will appear in the labels column, '&' will cut off the length of a tweet, etc. 

So my next approach will be to refactor my data cleaning code into a wrangle function and insert that into the FrankenBERT notebook. No CSVs will be needed, only the cleaned dataframes already ready-at-hand.

**Pull request merged**
