### PR TITLE
Refactored generated tweets code and changed PR template

### PR DESCRIPTION
**Pull request by JAaron93**
Naming: feature/ebignore-josh

Reviewers: Minimum 2 (Ryan, Josh, and/or Imani and/or 2 from WEB or DS respectively and not the person who submitted the PR)

Description: 
  What is the motivation for these changes?

- Needed to refactor code from my EDA synthetic tweets notebook
-  Had to use the over 200 tweets we manually labeled early on this month. Couldn't let those go to waste.
- Setting up a suitable notebook for training BERT just one last time before our time BW is over. Rank 2 was still a bit off.
- Lacking in visualizations. Needed a couple.
-  Takes hours to train BERT. We might have different GPUs when training the model independently. Would be interesting to see how long it takes on different GPUs
- Old PR template had to go

  What specific changes were made?

- Two reproducible functions for wrangling data, splitting it, and converting to a more secure and less memory-intensive file format.
- Reconnected our database labeler and pulled the >200 tweets our cohort manually labeled. 
- Generated more synthetic tweets for Rank 2 (~300 after cleaning and removing dupes). Needed just a bit more for BERT.
- Added a couple of visualizations for our compiled tweets
- Added timekeeping code to BERT and configured its input argument to take a pandas dataframe in place of a .csv
- Fixed return statement in 'clean_date' function in scraper.py at Rowen's request
- Finally updated the PR template to reflect our cohort

Submitter Checklist: 
  - [ ] Small scope (1-2 components/code cells/functions)
  - [ ] Not too many concerns in a single commit
  - [x] Removed extraneous comments (DB_URL, code in comments, print statements, to-dos, console.logs, extra fluff)
  - [x] Atomic, descriptive commit messages
  - [x] Consistent formatting

Reviewer Checklist:
  - [ ] Small scope (1-2 components/code cells/functions)
  - [ ] DB_URL, comments, print statements, to-dos, console.logs, extra fluff were removed
  - [ ] Give feedback no matter what conversations happened elsewhere, make sure to document here
  - [ ] Comment on the line of code itself (blue plus box) in files changed tab

### CODE REVIEW

**Review by rhiag — APPROVED** [review]
Great work Josh! 
Love the parquet format that you've incorporated. Seems more secure given that the data is read-only.
Also, the visualizations help with understanding the data better at a class level.

**Comment by JAaron93** [comment]
> Great work Josh!
> Love the parquet format that you've incorporated. Seems more secure given that the data is read-only.
> Also, the visualizations help with understanding the data better at a class level.

Thank you, Rhia! I really believed those visualizations were necessary. I'm hoping that donut chart can make it into the deployed site itself.

**Review by Iamlegend-Imani — APPROVED** [review]
This Parquet as an alternative to using the CSV was a phenonemal one her Joshua!

**Comment by Iamlegend-Imani** [comment]
The Visualization also help me better understand what is going on here! So i believe it will help with this alot!

**Pull request merged**
